import type { INodeProperties } from 'n8n-workflow';

export const updateOperation: INodeProperties[] = [
  {
    displayName: 'Update Fields',
    name: 'updateFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    displayOptions: {
      show: {
        resource: ['account'],
        operation: ['update'],
      },
    },
    options: [
      {
        displayName: 'Audio Transcriptions',
        name: 'audio_transcriptions',
        type: 'boolean',
        default: false,
        description:
          'Whether Captain transcribes incoming audio messages (Chatwoot Enterprise/Cloud with Captain)',
      },
      {
        displayName: 'Auto Resolve After (Minutes)',
        name: 'auto_resolve_after',
        type: 'number',
        typeOptions: {
          minValue: 0,
          maxValue: 1439856,
        },
        default: 0,
        description:
          'Minutes of inactivity after which open conversations are resolved automatically (10 to 1439856, e.g. 1440 = 1 day). 0 disables auto-resolve.',
      },
      {
        displayName: 'Auto Resolve Duration (Days, Deprecated)',
        name: 'auto_resolve_duration',
        type: 'number',
        typeOptions: {
          minValue: 0,
          maxValue: 999,
        },
        default: 0,
        description:
          'Deprecated: use Auto Resolve After (Minutes). Converted to minutes (days × 1440); 0 disables auto-resolve. Ignored when Auto Resolve After is set.',
      },
      {
        displayName: 'Auto Resolve Ignore Waiting',
        name: 'auto_resolve_ignore_waiting',
        type: 'boolean',
        default: false,
        description: 'Whether auto-resolve skips conversations that are waiting for an agent reply',
      },
      {
        displayName: 'Auto Resolve Label',
        name: 'auto_resolve_label',
        type: 'string',
        default: '',
        description: 'Label added to conversations when they are auto-resolved. Empty removes it.',
      },
      {
        displayName: 'Auto Resolve Message',
        name: 'auto_resolve_message',
        type: 'string',
        typeOptions: {
          rows: 3,
        },
        default: '',
        description:
          'Message sent to the contact when a conversation is auto-resolved. Empty disables the message.',
      },
      {
        displayName: 'Company Size',
        name: 'company_size',
        type: 'string',
        default: '',
        description: 'Company size stored in the account custom attributes',
      },
      {
        displayName: 'Domain',
        name: 'domain',
        type: 'string',
        default: '',
        description: 'Inbound email domain used to build reply-to addresses (max 100 characters)',
      },
      {
        displayName: 'Industry',
        name: 'industry',
        type: 'string',
        default: '',
        description: 'Industry stored in the account custom attributes',
      },
      {
        displayName: 'Locale',
        name: 'locale',
        type: 'options',
        options: [
          { name: 'Arabic', value: 'ar' },
          { name: 'Bulgarian', value: 'bg' },
          { name: 'Catalan', value: 'ca' },
          {
            name: 'Chinese (Legacy Code, Sent as zh_CN)',
            value: 'zh',
            description: 'Kept for existing workflows; Chatwoot only accepts zh_CN or zh_TW',
          },
          { name: 'Chinese (Simplified)', value: 'zh_CN' },
          { name: 'Chinese (Traditional)', value: 'zh_TW' },
          { name: 'Czech', value: 'cs' },
          { name: 'Danish', value: 'da' },
          { name: 'Dutch', value: 'nl' },
          { name: 'English', value: 'en' },
          { name: 'Estonian', value: 'et' },
          { name: 'Finnish', value: 'fi' },
          { name: 'French', value: 'fr' },
          { name: 'German', value: 'de' },
          { name: 'Greek', value: 'el' },
          { name: 'Hebrew', value: 'he' },
          {
            name: 'Hindi (Disabled in Chatwoot)',
            value: 'hi',
            description:
              'Chatwoot disables this locale; the node reports an error if it is selected',
          },
          { name: 'Hungarian', value: 'hu' },
          { name: 'Icelandic', value: 'is' },
          { name: 'Indonesian', value: 'id' },
          { name: 'Italian', value: 'it' },
          { name: 'Japanese', value: 'ja' },
          { name: 'Korean', value: 'ko' },
          { name: 'Latvian', value: 'lv' },
          { name: 'Lithuanian', value: 'lt' },
          { name: 'Malayalam', value: 'ml' },
          { name: 'Norwegian', value: 'no' },
          { name: 'Persian', value: 'fa' },
          { name: 'Polish', value: 'pl' },
          { name: 'Portuguese', value: 'pt' },
          { name: 'Portuguese (Brazil)', value: 'pt_BR' },
          { name: 'Romanian', value: 'ro' },
          { name: 'Russian', value: 'ru' },
          { name: 'Serbian', value: 'sr' },
          { name: 'Slovak', value: 'sk' },
          { name: 'Slovenian', value: 'sl', description: 'Requires Chatwoot 4.17+' },
          { name: 'Spanish', value: 'es' },
          { name: 'Swedish', value: 'sv' },
          { name: 'Tamil', value: 'ta' },
          { name: 'Thai', value: 'th' },
          { name: 'Turkish', value: 'tr' },
          { name: 'Ukrainian', value: 'uk' },
          { name: 'Uzbek', value: 'uz', description: 'Requires Chatwoot 4.16+' },
          { name: 'Vietnamese', value: 'vi' },
        ],
        default: 'en',
        description: 'Default language of the account',
      },
      {
        displayName: 'Name',
        name: 'name',
        type: 'string',
        default: '',
        description: 'Name of the account',
      },
      {
        displayName: 'Support Email',
        name: 'support_email',
        type: 'string',
        placeholder: 'support@example.com',
        default: '',
        description: 'Support email address for the account',
      },
      {
        displayName: 'Timezone',
        name: 'timezone',
        type: 'string',
        default: '',
        placeholder: 'America/Mexico_City',
        description: 'Account timezone stored in the account custom attributes',
      },
      {
        displayName: 'Website',
        name: 'website',
        type: 'string',
        default: '',
        placeholder: 'https://example.com',
        description: 'Company website stored in the account custom attributes',
      },
    ],
  },
];
